server:
  port: ${PORT:8080}
  shutdown: graceful

spring:
  application:
    name: java-admin-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5432/java_admin}
    username: ${DB_USERNAME:app}
    password: ${DB_PASSWORD:app}
    hikari:
      maximum-pool-size: ${DB_POOL_MAX:10}
      connection-timeout: 3000
      validation-timeout: 1000
  flyway:
    enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  lifecycle:
    timeout-per-shutdown-phase: 20s

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db

logging:
  pattern:
    level: "%5p [requestId:%X{requestId:-}]"
